/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "send_coord.h"

char **
coord_1_svc(float *argp, struct svc_req *rqstp)
{

	static char* result;
	sprintf(result, "the number is %f", *argp);

	return &result;
}
